ALTER TABLE quan_ly_qc
  ADD COLUMN IF NOT EXISTS teacher_lms_id VARCHAR(120),
  ADD COLUMN IF NOT EXISTS teacher_username VARCHAR(255),
  ADD COLUMN IF NOT EXISTS teacher_code VARCHAR(120),
  ADD COLUMN IF NOT EXISTS teacher_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS raw_total_score NUMERIC(8,2),
  ADD COLUMN IF NOT EXISTS raw_max_score NUMERIC(8,2);
